#%RAML 1.0 NamedExample

{
    "status": {
        "code": "SUCCESS",
        "message": "Successfully Retrieved"
    },
    "data": [
        {
            "flight_code": "BA002",
            "airline_name": "Air India"
        },
        {
            "flight_code": "BA003",
            "airline_name": "Air India"
        },
        {
            "flight_code": "BA004",
            "airline_name": "Air India"
        }
    ]
}