#%RAML 1.0 NamedExample


  {
    "status": {
        "code": "SUCCESS",
        "message": "Successfully Added"
    },
    "data": [
        {
            "Departure_Airport": "POM",
            "Flight_Code": "BA007",
            "Price": 1400.00,
            "Departure_Date": "2017-03-15T20:30:00",
            "Aircraft_Type": "Airbus A18",
            "Seat_Availability": 200,
            "Airline_Name": "Air India",
            "Destination_Airport": "GKA"
        }
    ]
}
