#%RAML 1.0 NamedExample

{

  flight_code: "BA001",
  airline_name: "British Airways",
  departure_airport: "JFK",
  destination_airport: "LCY",
  departure_date: "2017-03-15 20:30:00",
  aircraft_type: "Airbus A318",
  seat_availability: 200,
  price: "1400.00"
 
}