#%RAML 1.0 NamedExample

{
    "status": {
        "code": "SUCCESS",
        "message": "Successfully Retrieved"
    },
    "data": [
        {
            "country": "United Kingdom",
            "city": "London",
            "Name": "London City Airport",
            "Destination_Airport": "LCY"
        },
        {
            "country": "United Kingdom",
            "city": "London",
            "Name": "London City Airport",
            "Destination_Airport": "LCY"
        },
        {
            "country": "United States",
            "city": "San Francisco",
            "Name": "San Francisco International Airport",
            "Destination_Airport": "SFO"
        }
    ]
}