#%RAML 1.0 NamedExample

{
    "status": {
        "code": "SUCCESS",
        "message": "Successfully Updated"
    },
    "data": [
        {
            "Departure_Airport": "HKG",
            "Flight_Code": "CX888",
            "Price": 2500.00,
            "Departure_Date": "2017-03-16T01:00:00",
            "Aircraft_Type": "Boeing 777-300ER",
            "Seat_Availability": 100,
            "Airline_Name": "Cathay Pacific",
            "Destination_Airport": "YVR"
        }
    ]
}